### PR TITLE
Updating ACHP

### PR DESCRIPTION
**Pull request by bo3mrh**
Working on updating ACHP code

### CODE REVIEW

**Comment by ibell** [comment]
Uhoh, you tried to commit 11,000 files :)  I don't think you wanted to do that

**Comment by bo3mrh** [comment]
I think I did something wrong. I don't know why I can't fork any more ?

**Comment by ibell** [comment]
Not sure, what error do you get?

**Comment by bo3mrh** [comment]
When I tried to fork, it just takes me to https://github.com/bo3mrh/ACHP-1 !!?

**Comment by ibell** [comment]
I think if you have bo3mrh/ACHP-1 checked out, you just need to delete the
.metadata and .pydev folders.

**Comment by bo3mrh** [comment]
Ian, 

I noticed that we have correlation for three different types of fins (herringbone, wavy louvered, and plain find). So, I added a if statement and corrected the validator to take a string of FinsType.
Does that make sense?
This is only updated for the condenser, and I will update the evaporator if you agree.

**Comment by ibell** [comment]
Ok, this looks good for the first commit, merging.

**Comment by ibell** [comment]
Sounds good to me

**Pull request merged**
